### ISSUE TITLE
how do i change the background color?

### ISSUE THREAD

**Issue by Maru-Yasa** [imanmalekian31/vue-bottom-navigation#13]
maybe you can add backgroundColor constructor too, for the customization, thankyou :)

**Comment by imanmalekian31** [comment]
Hi,
I added two props for you in the new version `1.3.4`
`    backgroundColor: {
      type: String,
      default: "#FFFFFF",
    },
    iconColor: {
      type: String,
      default: "#0000008A",
    },`

I would if you like it, give it a star :)
