### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by melvas6** [imanmalekian31/vue-bottom-navigation#15]
Hi, 
Thanks for this beautiful bottom-navigation component.

How can I integrate into a Nuxt application?

**Comment by imanmalekian31** [comment]
Hi,
I created a usage example project in this repo. I hope this helps.
https://github.com/imanmalekian31/bottom-navigation-usage-example

Best regards.

**Comment by melvas6** [comment]
Thank you
