### ISSUE TITLE
no effect of change v-model value

### ISSUE THREAD

**Issue by ildan95** [imanmalekian31/vue-bottom-navigation#16]
I use CurvedBottomNavigation:
`CurvedBottomNavigation(:options="navOptions" v-model="selected" replaceRoute)`

I try change `selected` value throw my code, but navigation doesn't work.

**Comment by imanmalekian31** [comment]
It is fixed in the new version (`2.3.4`)
Thank you.

**Comment by ildan95** [comment]
It doesn't work in Vue3
