### ISSUE TITLE
no effect of change v-model value in vue3

### ISSUE THREAD

**Issue by ildan95** [imanmalekian31/vue-bottom-navigation#19]
[Same bug](https://github.com/imanmalekian31/vue-bottom-navigation/issues/16) was in vue2

**Comment by matiasromantdf** [comment]
Same.
whenever the route is modified or a value of a "badge" is updated, the effect of the selected flap disappears.
in the same way if a value is set in data() for "selected" it always returns to the indicated index

**Comment by matiasromantdf** [comment]
bueno, investigando un poco el código descubrí que hace un $emit con los clicks que se llama "update", lo capturé enviando como parametro el index del boton. En el padre actualizas el valor de "selected"

**Comment by imanmalekian31** [comment]
I have released a new version, `3.0.0`, based on Vue 3. 
please check it out. 
I hope it will solve your problems.
