### ISSUE TITLE
Routing Configuration

### ISSUE THREAD

**Issue by MotionPhix** [imanmalekian31/vue-bottom-navigation#20]
Hello,
Firstly thanks for this awesome library. While it is straight-forward to set up, I find it hard to implement routing. I am thinking you should cover more scenarios in the documentation on how to implement routing. For example, I am using nuxtjs 2, and if i use
`path: {
name: 'home'
}` it doesn't work. It crashes. I am also using it in Laravel with vue 3 and Inertiajs. This doesn't work either. So can you document properly how to implement routing, covering at least usages in either nuxt js or just vue

**Comment by imanmalekian31** [comment]
Hi,
I found some bugs and fixed them but I think your problem is about SSR mode in nuxtjs 2. I created an example with nuxtjs 2 in this repository and I hope it is helpful for you. And about vue 3, I should create new package for vue 3 I don't have enough time
