### ISSUE TITLE
Feature Request: Update(id) event

### ISSUE THREAD

**Issue by Mashiane** [imanmalekian31/vue-bottom-navigation#22]
Hi there

I could have missed it, but I don't think I saw anything that talks about lib emitting the "update" event.
If its not documented, perhaps you might have to include it in the docs for cases where one does not necessary use a path for navigation.

Again, congrats, good job on this.

**Comment by imanmalekian31** [comment]
Hi man,
Thank you for caring, I added it to the guides and you can see it now.
