### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by mage1k99** [imanmalekian31/vue-bottom-navigation#24]
Your library looks great!

Can you add support for typescript by adding type definition files ?

**Comment by imanmalekian31** [comment]
Hi,
These days I'm so busy and I can't add it but in the long term, I will do that.
Also, you can contribute to add that :)

**Comment by mage1k99** [comment]
Thanks for the reply, will look into it

**Comment by imanmalekian31** [comment]
Hi fellow,
I've just added types and you can use the last version (`3.2.0`).
