### ISSUE TITLE
Can't see icons, but installed fontawesome 

### ISSUE THREAD

**Issue by ekc73** [imanmalekian31/vue-bottom-navigation#32]
Hi, I've been fiddling with this issue, but I am unable to see any icons despite installing fontawesome and following your guide. Is there something I'm doing wrong here? I'm in Vue3

![image](https://user-images.githubusercontent.com/79546406/234346190-59002533-bab7-4d9a-b224-7206ef51e36c.png)

**Page where I use nav bar**
![image](https://user-images.githubusercontent.com/79546406/234345572-63962872-a01b-45c9-9434-5d007604d40c.png)

**main.js**
![image](https://user-images.githubusercontent.com/79546406/234345884-d8dfa8fc-0dce-461f-81b8-7351da8bf5f7.png)

Without your code, I am able to import the fontawesome icons just fine, but one I call bottomNavigation Vue it messes up.

**Comment by imanmalekian31** [comment]
Hi,
I guess it happened because I used the tag `i` for rendering the fontawesome icons and you have registered it as `font-awesome-icon` component.
please use `icon slot` to handle this.
https://vue-bottom-navigation.netlify.app/guide/swipe#slots

**Comment by imanmalekian31** [comment]
I want to close the issue, Did it solved?

**Comment by ekc73** [comment]
> I want to close the issue, Did it solved?

yes! thank you

**Comment by ribrewguy** [comment]
While this works for level 1 menu items, it doesn't appear to work for child icons. Is there a way to apply the template to the childs values?
