### ISSUE TITLE
This CurvedProps type is already in types directory

### ISSUE THREAD

**Issue by EdgarMC100** [imanmalekian31/vue-bottom-navigation#33]
https://github.com/imanmalekian31/vue-bottom-navigation/blob/d68064f2015f1d4b11b89e8ca48dfd044992081e/src/components/CurvedBottomNavigation.vue#L83

**Comment by imanmalekian31** [comment]
Hi, I know that. I had a problem when I wanted to build and It has something to do with `CurvedProps` because I've defined options in it as a `CurvedOption`. 
I couldn't fix that so I defined it in the component to solve it temporarily.
If you can help me, I would appreciate it.
