### ISSUE TITLE
How to properly recalculate sweep traveling distance ?

### ISSUE THREAD

**Issue by NeroN7F** [imanmalekian31/vue-bottom-navigation#7]
Hi! Basicaly, I want to decrease width of the navigation to 50% for larger screens, but when I doing it through css 

`
.btn-containrt_foreground {
  width: 50% !important; }
`

I'm facing with an issue. Sweep doesnt slides correctly. How I understood it's logics, originaly it ordered to travel within a container width, 100% by default

`      const containerWidth =
        document.querySelector(".btn-containrt").offsetWidth ||
        window.innerWidth;
`

`

      document.getElementById("sweep").style.left = ${containerWidth / this.options.length / 4 - 135 / 2}px

`

 Unfortunately, didn't managed to do it properly. Could you hint me with answer please ?
Thank you !

**Comment by imanmalekian31** [comment]
Hi, 
I have checked it and it was ok and didn't have any problem with the following style:
`.btn-containrt_foreground { width: 50% !important; }`
If it's possible for you, call me on telegram to scrutinize your problem.
it's my telegram id: @imanmalekian
