### ISSUE TITLE
I kindly request a <script> version of your vue-bottom-navigation

### ISSUE THREAD

**Issue by Mashiane** [imanmalekian31/vue-bottom-navigation#9]
Hi there

Can I please get a compiled version of this to use in the <script> tag?

Thanks.

**Comment by opeolluwa** [comment]
The bare code? compactible with plain HTML ?

**Comment by Mashiane** [comment]
Thank you so much. Sorry I should have indicate for which Vue2 version.

As soon as I learn Vue3, will use these ones. Can you please avail for Vue 2? Thanks so much!
